# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default
  demands:
   - agent.name -equals DESKTOP-57RMBA3

variables:
  projectFolder: "src/react"
  buildOutputFolder: "src/react/build"

steps:
- script: |
    pushd $(projectFolder) && npm install && popd
    pushd $(projectFolder) && npm run build && popd

- task: CopyFiles@2
  inputs:
    sourceFolder: "$(buildOutputFolder)"
    contents: "**/*"
    targetFolder: "$(Build.ArtifactStagingDirectory)"
    cleanTargetFolder: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: $(Build.ArtifactStagingDirectory)
    archiveType: "zip"
    archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"